---
#r tasks file for roles/k3s
- name: Install k3s (server)
  shell: |
    curl -sfL https://get.k3s.io | \
    INSTALL_K3S_EXEC="server \
      --disable traefik \
      --disable servicelb" \
    sh -
  args:
    creates: /usr/local/bin/k3s

- name: Ensure k3s service is enabled and started
  systemd:
    name: k3s
    enabled: yes
    state: started

- name: Create kube config directory
  file:
    path: /home/{{ lab_user }}/.kube
    state: directory
    owner: "{{ lab_user }}"
    mode: "0755"

- name: Copy kubeconfig for user
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/{{ lab_user }}/.kube/config
    remote_src: yes
    owner: "{{ lab_user }}"
    mode: "0644"

- name: Fix kubeconfig server address
  replace:
    path: /home/{{ lab_user }}/.kube/config
    regexp: '127.0.0.1'
    replace: 'localhost'

